version: '3'
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
#    environment:
#      - PORT: ${DIAB_PORT}
#      - DB_URL: ${DIAB_DB_URL}
#      - JWT_SECRET: ${DIAB_JWT_SECRET}
