version: '3'
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
#    environment:
#      - PORT: ${DIAB_PORT}
#      - DB_URL: ${DIAB_DB_URL}
#      - JWT_SECRET: ${DIAB_JWT_SECRET}
  integrations:
    build:
      context: ./backend-integrations
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9001:9001"
#    environment:
#      - PORT: 9001
#      - EDAMAM_ID: ${DIAB_EDAMAM_ID}
#      - EDAMAM_KEY: ${DIAB_EDAMAM_KEY}
#      - NUTRITIONIX_ID: ${DIAB_EDAMAM_ID}
#      - NUTRITIONIX_KEY: ${DIAB_EDAMAM_KEY}